### ISSUE TITLE
Qucs Triangle Wave Example won't work Qucs-S

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#1050]
I have been having issues making I/V Triangle sub-circuits that work in ngspice and qucsator-rf.

1) netlist created for "Triangle_i_tran.sch" has an extraneous "-1" that causes ngspice errors. I flipped polarity of I1 and "-1" is still there. Send netlist to DuSpice after deleting -1 and simulation runs but data is garbage. This may effect #1046

2) I went back to Qucs 0.0.20 and "Triangle_Wave_Generator.sch" works. Try Triangle_Wave_Generator.sch in Qucs-S, qucsator-rf and it has multiple errors. Ideal Rectangular Current Sources doesn't work in qucsator-rf

![2024-11-08_124509](https://github.com/user-attachments/assets/734974aa-c91d-47e6-801d-51eca41942c2)
![2024-11-08_124342](https://github.com/user-attachments/assets/f4a813b1-c8b9-43d6-b827-560b0ac5e9f3)
![2024-11-08_124135](https://github.com/user-attachments/assets/efebe8f9-0bb8-4f85-b90b-d6a37755059c)

[Waveforms_prj.zip](https://github.com/user-attachments/files/17682389/Waveforms_prj.zip)

**Comment by ra3xdh** [comment]
The irect simulation error fixed by #1059.  The triangle wave simulation example works on my machine.
![image](https://github.com/user-attachments/assets/160a1793-29bb-42b8-ac11-fbbb944d7242)

**Comment by tomhajjar** [comment]
Have you updated the "nightly"? The latest from 35min ago hasn't fixed issues...

**Comment by ra3xdh** [comment]
Everything should be updated automatically. The latest build from `current` branch works as expected.

**Comment by ra3xdh** [comment]
Use the continuous release from 18:18UTC

**Comment by tomhajjar** [comment]
Still having issue with "Triangle_v_tran_qucs.sch". I am checking my work in Qucs and Qucs-S
